mwapp:
  appid: commodity
  version: 1.0.0

security:
  exclude:

pandora:
  # 文件路径 示例（ Windows配置D:/pandora/uploadPath，Linux配置 /home/pandora/uploadPath）
  profile: /var/eerp/commodity/uploadPath

base-system:
  url:

server:
  port: 8084
  servlet:
    context-path: /commodity/
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
      min-spare: 10

spring:
  devtools:
    restart:
      #热部署开关
      enabled: true
      trigger-file: .trigger

  profiles:
    active: prod

  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 20MB
      # 设置总上传的文件大小
      max-request-size: 20MB

  # redis 配置
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    database: 0
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      indent_output: true
      fail_on_empty_beans: false
    defaultPropertyInclusion: NON_NULL
    deserialization:
      fail_on_unknown_properties: false
    parser:
      allow_unquoted_control_chars: true
      allow_single_quotes: true
    time-zone: GMT+8
    locale: zh_CN

  task:
    execution:
      thread-name-prefix: MW-TASK-
      pool:
        core-size: 8
        max-size: 20
        queue-capacity: 200

    scheduling:
      thread-name-prefix: MW-SCHEDULE-
      pool:
        size: 3

mybatis:
  type-aliases-package: com.eerp.commodity.domin
  mapper-locations: classpath:mybatis/**/*Mapper.xml
  #config-location: classpath:mybatis/mybatis-config.xml
  configuration:
    cache-enabled: true
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    default-executor-type: reuse
    #map-underscore-to-camel-case: true

